project:
  type: website

website:
  navbar:
    logo: /assets/bluelogo.svg
    left:
      - href: verticals.qmd
        text: Solutions
      - href: methods.qmd
        text: Our Method
      # - href: example.qmd
      #   text: Example
      - href: posts.qmd
        text: Blog
      - href: about.qmd
        text: About Us

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom-dark.scss] # Darkly is Bootstrap's dark theme
    css:
      - output.css
      - styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="icon" type="image/svg" href="/assets/favicon.svg"/>
          <script>
            function toggleDarkMode() {
              document.body.classList.toggle('dark');
              // Store preference
              if (document.body.classList.contains('dark')) {
                localStorage.setItem('quarto-color-scheme', 'dark');
              } else {
                localStorage.setItem('quarto-color-scheme', 'light');
              }
            }

            // Check for stored preference
            if (localStorage.getItem('quarto-color-scheme') === 'dark') {
              document.body.classList.add('dark');
            }
          </script>
