project:
  type: website
  render:
    - "*.qmd"
    - "posts/"
    - "!AGENTS.md"

website:
  title: univ.ai
  site-url: https://univ.ai
  open-graph: true
  navbar:
    title: false
    logo: /assets/bluelogo.svg
    left:
      - href: verticals.qmd
        text: Solutions
      - href: methods.qmd
        text: Our Method
      # - href: example.qmd
      #   text: Example
      - href: posts.qmd
        text: Blog
      - href: about.qmd
        text: About Us

format:
  html:
    theme:
      light: styles/modern-light.scss
      dark: styles/modern-dark.scss
    css:
      - styles.css
    toc: true
    include-in-header:
      - includes/fonts.html
      - text: |
          <link rel="icon" type="image/svg+xml" href="/assets/bluelogo.svg"/>
