[project]
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "website"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]
build-dev = "pixi run npm run build-dev"
build = "pixi run npm run build"

[dependencies]
python = ">=3.13.1,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.1,<3"
scipy = ">=1.15.1,<2"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.1.1,<2"
scikit-learn = ">=1.6.1,<2"
nodejs = ">=22.12.0,<23"
quarto = ">=1.6.40,<2"

[target.win-64.dependencies]
python = ">=3.13.1,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.2,<3"
scipy = ">=1.15.1,<2"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.1.1,<2"
scikit-learn = ">=1.6.1,<2"
nodejs = ">=22.13.0,<23"
quarto = ">=1.6.40,<2"

[target.linux-64.dependencies]
python = ">=3.13.1,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.2,<3"
scipy = ">=1.15.1,<2"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.1.1,<2"
scikit-learn = ">=1.6.1,<2"
nodejs = ">=22.12.0,<23"
quarto = ">=1.6.40,<2"
